import { pgTable, text, serial, integer, timestamp, real, jsonb } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const basicSurveysTable = pgTable("basic_surveys", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull(),
  gender: text("gender").notNull(),
  goal: text("goal").notNull(),
  hormonalDisorder: text("hormonal_disorder").notNull(),
  lifestyle: text("lifestyle").notNull(),
  age: integer("age").notNull(),
  height: integer("height").notNull(),
  weight: real("weight").notNull(),
  targetWeight: real("target_weight").notNull(),
  sport: text("sport"),
  dailySteps: integer("daily_steps").notNull(),
  cardioMinutesPerWeek: integer("cardio_minutes_per_week").notNull(),
  strengthMinutesPerWeek: integer("strength_minutes_per_week").notNull(),
  waistCm: real("waist_cm"),
  weightChangePast12Months: text("weight_change_past_12_months"),
  energyMorning: integer("energy_morning"),
  energyAfternoon: integer("energy_afternoon"),
  energyEvening: integer("energy_evening"),
  sleepFallingAsleep: text("sleep_falling_asleep"),
  sleepNightWakeups: text("sleep_night_wakeups"),
  sleepRestfulness: text("sleep_restfulness"),
  chronicStressLevel: integer("chronic_stress_level"),
  caffeineIntake: text("caffeine_intake"),
  bloatingAfterEating: text("bloating_after_eating"),
  gasForming: text("gas_forming"),
  heavinessAfterEating: text("heaviness_after_eating"),
  stoolRegularity: text("stool_regularity"),
  foodReactions: jsonb("food_reactions").$type<string[]>().default([]),
  skinHairNailSymptoms: jsonb("skin_hair_nail_symptoms").$type<string[]>().default([]),
  illnessFrequency: text("illness_frequency"),
  recoverySpeed: text("recovery_speed"),
  chronicInflammations: jsonb("chronic_inflammations").$type<string[]>().default([]),
  allergies: text("allergies"),
  generalSymptoms: jsonb("general_symptoms").$type<string[]>().default([]),
  menstrualRegularity: text("menstrual_regularity"),
  pmsLevel: text("pms_level"),
  menstrualPain: text("menstrual_pain"),
  edemaLevel: text("edema_level"),
  morningErections: text("morning_erections"),
  trainingRecovery: text("training_recovery"),
  proteinFrequency: text("protein_frequency"),
  fishFrequency: text("fish_frequency"),
  vegetableFrequency: text("vegetable_frequency"),
  fruitFrequency: text("fruit_frequency"),
  wholeGrainFrequency: text("whole_grain_frequency"),
  carbType: text("carb_type"),
  bmr: integer("bmr").notNull(),
  tdee: integer("tdee").notNull(),
  targetCalories: integer("target_calories").notNull(),
  proteins: integer("proteins").notNull(),
  fats: integer("fats").notNull(),
  carbs: integer("carbs").notNull(),
  bmi: real("bmi").notNull(),
  bmiCategory: text("bmi_category").notNull(),
  weightToGoal: real("weight_to_goal").notNull(),
  totalDeficitNeeded: integer("total_deficit_needed").notNull(),
  estimatedMonths: integer("estimated_months").notNull(),
  progressBlockers: jsonb("progress_blockers").$type<string[]>().default([]),
  moderateDeficit: integer("moderate_deficit"),
  aggressiveDeficit: integer("aggressive_deficit"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const insertBasicSurveySchema = createInsertSchema(basicSurveysTable).omit({ id: true, createdAt: true });
export type InsertBasicSurvey = z.infer<typeof insertBasicSurveySchema>;
export type BasicSurvey = typeof basicSurveysTable.$inferSelect;
